name: python testing and linting

on:
  push:
    branches:
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Step -- 1.
        uses: actions/checkout@v4

      - name: Step -- 2.
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Step -- 3.
        run: pip3 install --upgrade pip && pip3 install --no-cache-dir --upgrade tox

      - name: Step -- 4.
        run: tox && tox -e lint
